name: CrashClaim
version: ${version}
description: A modern advanced user oriented claiming system
author: Chasewhip
main: net.crashcraft.crashclaim.CrashClaim
api-version: "1.21"
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      required: false
    PlaceholderAPI:
      required: false
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    GahvilaCore:
      required: true